language: python
python: 
    - "3.5"
env:
    matrix:
        - DJANGO="Django<=1.10,<1.11"
        - DJANGO="Django>=1.11,<1.12"
    branches:
        only:
            - master
install:
    - pip install "$DJANGO"
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install coverage

before_script:
    - python manage.py test

after_success:
    - coveralls    
