language: python
python:
    - "3.5"
env:
    matrix:
        - DJANGO="Django>=1.11"
    branches:
        only:
            - master
            - develop
install:
    - pip install "$DJANGO"
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install coverage

script:
    - python manage.py test
after_success:
    - coveralls
